box::use(dplyr)
box::use(janitor)
box::use(rlang)

box::use(cs = ../utils/cloud_storage)
box::use(./delete_campaign_content[delete_campaign_content])

#' Generate campaigns content data frame
#'
#' Used when generating and updating campaigns. Creates all of the content used
#' in templates and campaigns, from the subject line of the email to the plots
#' and text contained within the body.
#'
#' @param df_alerts Data frame of alerts
#' @param df_wrangled Data frame of wrangled data
#' @param df_raw Data frame of raw data
#' @param subject_fn Function to create subject and title information for the campaign
#' @param plot_fn Function to create plots for the campaign
#' @param map_fn Function to create maps for the campaign
#' @param plot2_fn Function to create the second plot for a campaign
#' @param other_images_fn Function to add other images to the campaign
#' @param summary_fn Function to add text summaries to the campaign
#' @param info_fn Function to add info to the campaign
#' @param empty Whether or not the returned data frame should be empty or not.
#'     Used to create empty sections to update existing pending campaigns.
#'
#' @export
generate_campaign_content <- function(
    df_alerts,
    df_wrangled,
    df_raw,
    plot_fn = NULL,
    map_fn = NULL,
    plot2_fn = NULL,
    other_images_fn = NULL,
    summary_fn = NULL,
    info_fn = NULL,
    empty = FALSE
) {
  df_campaigns <- df_alerts |>
    generate_images(df_wrangled, df_raw, plot_fn, "plot", empty) |>
    generate_images(df_wrangled, df_raw, map_fn, "map", empty) |>
    generate_images(df_wrangled, df_raw, plot2_fn, "plot2", empty) |>
    generate_other_images(df_wrangled, df_raw, other_images_fn, empty) |>
    generate_summary(df_wrangled, df_raw, summary_fn, empty) |>
    generate_info(df_wrangled, df_raw, info_fn, empty) |>
    validate_campaign_content()
}


#' Generate images for inclusion in alerts
#'
#' Generates images for inclusions in the alerts. If `fn` is `NULL`, returns an
#' empty dataset. Otherwise, the `fn` is run to generate plots for the passed in
#' alerts data frame, and returns three columns for the title, ID, and URL of
#' the plots specifically.
#'
#' @param df_alerts Alerts data frame
#' @param df_wrangled Wrangled data frame
#' @param df_raw Raw data frame
#' @param fn Plotting function
#' @param image_name Name of the image to generate, either a `plot`, `map`, or `plot2`,
#'     corresponding with the final columns in a campaigns data frame.
#' @param empty Whether or not to return an empty data frame if `fn` is `NULL`.
#'
#' @returns Data frame of title, ID, and URLs for the generated images.
generate_images <- function(df_alerts, df_wrangled, df_raw, fn = NULL, image_name = c("plot", "map", "plot2"), empty = FALSE) {
  image_name <- rlang$arg_match(image_name)
  generate_section(
    df_alerts = df_alerts,
    df_wrangled = df_wrangled,
    df_raw = df_raw,
    fn = fn,
    fn_name = deparse(substitute(fn)),
    null_return = dplyr$tibble(
      "{image_name}_title" := NA_character_,
      "{image_name}_id" := NA_character_,
      "{image_name}_url" := NA_character_,
      .rows = nrow(df_alerts)
    ),
    empty = empty
  )
}

#' Generate IDs and URLs for other images to be included in the email
#'
#' Generates IDs and URLs for other images to be included in the email. These are
#' those sourced from elsewhere, not generated by HDX Signals, so do not have a
#' title but instead a caption that might indicate where it's from, what it covers,
#' etc.
#'
#' @param df Alerts data frame
#' @param df_wrangled Wrangled data frame
#' @param fn Function to generate the linkages to other images
#' @param empty Whether or not to return an empty data frame if `fn` is `NULL`.
generate_other_images <- function(df_alerts, df_wrangled, df_raw, fn = NULL, empty = FALSE) {
  generate_section(
    df_alerts = df_alerts,
    df_wrangled = df_wrangled,
    df_raw = df_raw,
    fn = fn,
    fn_name = deparse(substitute(fn)),
    null_return = dplyr$tibble(
      other_images_ids = NA_character_,
      other_images_urls = NA_character_,
      other_images_captions = NA_character_,
      .rows = nrow(df_alerts)
    ),
    empty = empty
  )
}

#' Generate summaries for campaigns
#'
#' Generates the short and long summaries for the campaigns.
#'
#' @param df Alerts data frame
#' @param df_wrangled Wrangled data frame
#' @param fn Function to generate the linkages to other images
#' @param empty Whether or not to return an empty data frame if `fn` is `NULL`.
generate_summary <- function(df_alerts, df_wrangled, df_raw, fn = NULL, empty = FALSE) {
  generate_section(
    df_alerts = df_alerts,
    df_wrangled = df_wrangled,
    df_raw = df_raw,
    fn = fn,
    fn_name = deparse(substitute(fn)),
    null_return = dplyr$tibble(
      summary_long = NA_character_,
      summary_short = NA_character_,
      .rows = nrow(df_alerts)
    ),
    empty = empty
  )
}

#' Generate info for alerts
#'
#' Generates info for alerts. Includes the different URL links for the alerts,
#' to HDX, to other sources, and the further information section in the alerts.
#'
#' @param df Alerts data frame
#' @param df_wrangled Wrangled data frame
#' @param fn Content generating function
#' @param empty Whether or not to return an empty data frame
generate_info <- function(df_alerts, df_wrangled, df_raw, fn = NULL, empty = FALSE) {
  generate_section(
    df_alerts = df_alerts,
    df_wrangled = df_wrangled,
    df_raw = df_raw,
    fn = fn,
    fn_name = deparse(substitute(fn)),
    null_return = dplyr$tibble(
      hdx_url = NA_character_,
      source_url = NA_character_,
      other_urls = NA_character_,
      further_information = NA_character_,
      .rows = nrow(df_alerts)
    ),
    empty = empty
  )
}

#' Generate sections for alerts
#'
#' Generates a section for alerts. Simply calls the `fn` on the alerts data frame
#' `df`. However, if `fn` is `NULL` and `empty` is `TRUE`, returns an empty data
#' frame, otherwise returns the `null_return`. If `fn` is a function, then runs
#' the function and returns that.
#'
#' This function is used to ensure that when content is created but an error
#' occurs down the line, the previously uploaded content to Mailchimp is deleted
#' and removed.
#'
#' @param df_alerts Alerts data frame
#' @param df_wrangled Wrangled data frame
#' @param df_raw Raw data frame
#' @param fn Content generating function
#' @param fn_name Name of the function
#' @param null_return Value to return if `fn` is `NULL`
#' @param empty Whether or not to return an empty data frame
generate_section <- function(df_alerts, df_wrangled, df_raw, fn, fn_name, null_return, empty) {
  if (is.null(fn) || nrow(df_alerts) == 0) {
    if (empty) {
      section <- dplyr$tibble(.rows = nrow(df_alerts))
    } else {
      section <- null_return
    }
  } else {
    section <- fn(df_alerts, df_wrangled, df_raw)
  }

  # if we error out, ensure previously generated content is deleted from Mailchimp

  if (any(section == "ERROR", na.rm = TRUE)) {
    delete_campaign_content(df_alerts)
    delete_campaign_content(section)
    stop(
      "Errors generated in ",
      fn_name,
      ". All generated campaign content deleted. Please fix and start again.",
      call. = FALSE
    )
  }
  dplyr$bind_cols(df_alerts, section)
}

#' Validate and arrange campaigns data frame
#'
#' Validates that all columns are present and of the correct type. Also re-arranges
#' column orders in case the dataset is being updated.
#'
#' @param df_campaigns_content Campaigns content data frame
#'
#' @returns Arranged campaigns data frame
validate_campaign_content <- function(df_campaigns_content) {
  df_check <- dplyr$tibble(
    iso3 = NA_character_,
    country = NA_character_,
    region = NA_character_,
    hrp_country = NA,
    lat = NA_real_,
    lon = NA_real_,
    indicator_name = NA_character_,
    indicator_source = NA_character_,
    indicator_id = NA_character_,
    date = as.Date(x = integer(0), origin = "1970-01-01"),
    alert_level_numeric = NA_integer_,
    alert_level = NA_character_,
    value = NA_real_,
    plot_title = NA_character_,
    plot_id = NA_character_,
    plot_url = NA_character_,
    map_title = NA_character_,
    map_id = NA_character_,
    map_url = NA_character_,
    plot2_title = NA_character_,
    plot2_id = NA_character_,
    plot2_url = NA_character_,
    other_images_ids = NA_character_,
    other_images_urls = NA_character_,
    other_images_captions = NA_character_,
    summary_long = NA_character_,
    summary_short = NA_character_,
    hdx_url = NA_character_,
    source_url = NA_character_,
    other_urls = NA_character_,
    further_information = NA_character_
  )

  if (!janitor$compare_df_cols_same(df_campaigns_content, df_check, bind_method = "rbind")) {
    delete_campaign_content(df_campaigns_content)
    stop(
      "Campaign data frame does not have the required columns and column types, ",
      "please check how it was generated.",
      call. = FALSE
    )
  }

  # arrange data frame columns to match `df_check`
  df_campaigns_content[,names(df_check)]
}
