box::use(glue)
box::use(purrr)
box::use(stringr)

box::use(./text_block)
box::use(./boxed_text_block)
box::use(./image_block)
box::use(./line_block)
box::use(./summary_block)
box::use(./further_info_block)
box::use(../mailchimp/audience)

#' Create country block
#'
#' Create a country block with information passed in. The only required fields
#' are `iso3` and `country`, although typically all will be passed (even if missing)
#' direct from alerts datasets. The `iso3` code is used to generate the conditional
#' merge for MailChimp so the country only appears to interested users.
#'
#' @param iso3 ISO3 code
#' @param country Country name, used for header of section
#' @param plot_title Plot title, used as alt text for plot
#' @param plot_url URL to plot to include
#' @param map_title Map title, used as alt text for plot
#' @param map_url URL to map to include
#' @param plot2_title Plot2 title, used as alt text for plot
#' @param plot2_url URL to plot2 to include
#' @param other_images_urls List of other images to include, separated by ;
#' @param other_images_captions List of other images captions, separated by ;
#' @param summary Summary text generated by AI
#' @param further_information Further information text
#' @param use_conditions Whether or not to use conditional merge to
#'      wrap text in Mailchimp conditions for those countries.
#'
#' @returns HTML for country block
#'
#' @export
add_country <- function(
    iso3,
    country,
    plot_title = "",
    plot_url = "",
    map_title = "",
    map_url = "",
    plot2_title = "",
    plot2_url = "",
    other_images_urls = "",
    other_images_captions = "",
    summary = "",
    further_information = "",
    use_conditions = FALSE
) {
  paste0(
    text_block$add_text(header = country, header_class = "title"),
    image_block$add_image(src = plot_url, alt = plot_title),
    image_block$add_image(src = map_url, alt = map_title),
    image_block$add_image(src = plot2_url, alt = plot2_title),
    purrr$map2_chr(
      .x = stringr$str_split(other_images_urls, ";"),
      .y = stringr$str_split(other_images_captions, ";"),
      .f = \(src, caption) image_block$add_image(src = src, caption = caption)
    ),
    summary_block$add_summary(text = summary),
    further_info_block$add_further_info(text = further_information),
    line_block$add_line()
  ) |>
    conditional_merge(
      iso3 = iso3,
      use_conditions = use_conditions
    )
}

#' Wraps text in conditional merge text
#'
#' Wraps text in conditional merge text based on the ISO3 code passed in. This is
#' also wrapped in text so the conditional merge tags only appear if the campaign
#' is viewed in the email! Thus, the archive page can show all content. If
#' `use_conditions` is `FALSE`, then the text is just returned as is. This is
#' because archive links don't work.
conditional_merge <- function(text, iso3, use_conditions) {
  if (use_conditions) {
    regions <- audience$mc_interests_iso3(iso3, "conditional_blocks")
    opening_tag <- glue$glue("*|INTERESTED:Regions of interest:{regions}|*")
    closing_tag <- "*|END:INTERESTED|*"
    paste0(
      opening_tag,
      text,
      closing_tag
    )
  } else {
    text
  }
}
