box::use(purrr)

box::use(./country_block)
box::use(./intro_block)
box::use(./text_block)
box::use(./line_block)

#' Create email body
#'
#' Create email body. Uses a set of vectors to create country blocks.
#'
#' @param title Shock title text to go next to HDX Signals at the top of the email
#' @param iso3 Vector of ISO3 codes
#' @param country Vector of country names
#' @param alert_level Vector of alert levels
#' @param message Vector of messages
#' @param plot Vector of URLs to plot to include
#' @param map Vector of URLs to map to include
#' @param other_images Vector of lists of other images to include, separated by ;
#' @param summary_long Vector of summary texts generated by AI, to be used in
#'     the country blocks as summary text.
#' @param summary_short Vector of summary texts generated by AI, to be used in
#'     the table of contents as a quick info block.
#' @param further_information Vector of further information texts
#' @param use_conditions Whether to wrap the country blocks in conditional logic
#'     so they only appear to specific subscribers. However, if wrapped in logic,
#'     those blocks will not appear in the archived URL.
#'
#' @export
create_body <- function(
    title,
    iso3,
    country,
    alert_level,
    plot_title = "",
    plot_url = "",
    map_title = "",
    map_url = "",
    plot2_title = "",
    plot2_url = "",
    other_images_urls = "",
    other_images_captions = "",
    summary_long = "",
    summary_short = "",
    further_information = "",
    use_conditions = FALSE
) {
  paste0(
    intro_block$add_intro(
      title = title,
      iso3 = iso3,
      country = country,
      alert_level = alert_level,
      summary_short = summary_short,
      use_conditions = use_conditions
    ),
    line_block$add_line(),
    paste(
      purrr$pmap_chr(
        .l = list(
          iso3 = iso3,
          country = country,
          alert_level = alert_level,
          plot_title = plot_title,
          plot_url = plot_url,
          map_title = map_title,
          map_url = map_url,
          plot2_title = plot2_title,
          plot2_url = plot2_url,
          other_images_urls = other_images_urls,
          other_images_captions = other_images_captions,
          summary_long = summary_long,
          further_information = further_information,
          use_conditions = use_conditions
        ),
        .f = country_block$add_country
      ),
      collapse = "\n"
    ),
    text_block$add_text(
      text = paste0(
        "Full documentation and source code for HDX Signals is available on ",
        "<a href='https://github.com/OCHA-DAP/hdx-signals'>GitHub</a>. Reach ",
        "out to <a href='mailto:",
        Sys.getenv("HDX_SIGNALS_EMAIL"),
        "'>",
        Sys.getenv("HDX_SIGNALS_EMAIL"),
        "</a> ",
        "with any questions, comments, or other feedback."
      )
    )
  )
}

