box::use(purrr)

box::use(./country_block)
box::use(./text_block)

#' Create email body
#'
#' Create email body. Uses a set of vectors to create country blocks.
#'
#' @param shock_title Shock title text to go next to HDX Signals at the top of the email
#' @param iso3 Vector of ISO3 codes
#' @param country Vector of country names
#' @param message Vector of messages
#' @param plot Vector of URLs to plot to include
#' @param map Vector of URLs to map to include
#' @param other_images Vector of lists of other images to include, separated by ;
#' @param summary Vector of summary texts generated by AI
#' @param further_information Vector of further information texts
#'
#' @export
create_body <- function(
    shock_title,
    iso3,
    country,
    message = "",
    plot = "",
    map = "",
    other_images = "",
    summary = "",
    further_information = ""
) {
  paste0(
    text_block$add_text(
      text = "Signals detected in:\n*|MC:TOC|*",
      header = paste("HDX Signals:", shock_title),
      header_level = 1,
      header_class = "null"
    ),
    purrr$pmap_chr(
      .l = list(
        iso3 = iso3,
        country = country,
        message = message,
        plot = plot,
        map = map,
        other_images = other_images,
        summary = summary,
        further_information = further_information
      ),
      .f = country_block$add_country
    )
  )
}

