box::use(
  purrr,
  glue
)

box::use(
  src/email/components/location_block,
  src/email/components/intro_block,
  src/email/components/text_block,
  src/email/components/line_block
)

#' Create email body
#'
#' Create email body. Uses a set of vectors to create location blocks. Requires
#' the `HS_EMAIL` environment variable to specify the response email
#' and `HS_SURVEY_LINK` to link to our feedback survey.
#'
#' @param title Shock title text to go next to HDX Signals at the top of the email
#' @param iso3 Vector of ISO3 codes
#' @param location Vector of location names
#' @param message Vector of messages
#' @param plot Vector of URLs to plot to include
#' @param map Vector of URLs to map to include
#' @param other_images Vector of lists of other images to include, separated by ;
#' @param summary_long Vector of summary texts generated by AI, to be used in
#'     the location blocks as summary text.
#' @param summary_short Vector of summary texts generated by AI, to be used in
#'     the table of contents as a quick info block.
#' @param summary_source Vector of source information for summary text, used in
#'     providing caveats in the situation summary text.
#' @param further_information Vector of further information texts
#' @param use_conditions Whether to wrap the location blocks in conditional logic
#'     so they only appear to specific subscribers. However, if wrapped in logic,
#'     those blocks will not appear in the archived URL.
#'
#' @export
create_body <- function(
    campaign_details,
    df_campaign_content,
    use_conditions = FALSE) {
  paste0(
    intro_block$add_intro(
      title = campaign_details$title,
      iso3 = df_campaign_content$iso3,
      location = df_campaign_content$location,
      summary_short = df_campaign_content$summary_short,
      use_conditions = use_conditions
    ),
    line_block$add_line(),
    paste(
      purrr$pmap_chr(
        .l = list(
          iso3 = df_campaign_content$iso3,
          location = df_campaign_content$location,
          plot_title = df_campaign_content$plot_title,
          plot_url = df_campaign_content$plot_url,
          map_title = df_campaign_content$map_title,
          map_url = df_campaign_content$map_url,
          plot2_title = df_campaign_content$plot2_title,
          plot2_url = df_campaign_content$plot2_url,
          other_images_urls = df_campaign_content$other_images_urls,
          other_images_captions = df_campaign_content$other_images_captions,
          summary_long = df_campaign_content$summary_long,
          summary_source = df_campaign_content$summary_source,
          further_information = df_campaign_content$further_information,
          use_conditions = use_conditions
        ),
        .f = location_block$add_location
      ),
      collapse = "\n"
    ),
    text_block$add_text(
      text = glue$glue(
        "Read more about Signals on HDX's <a href='https://data.humdata.org/signals'>",
        "website</a> and find all source code on ",
        "<a href='https://github.com/OCHA-DAP/hdx-signals'>GitHub</a>. Provide ",
        "feedback through our <a href='{Sys.getenv('HS_SURVEY_LINK')}'>",
        "user survey</a>, or reach out to <a href='mailto:{Sys.getenv('HS_EMAIL')}",
        "'>{Sys.getenv('HS_EMAIL')}</a> with any questions, comments, or other ",
        "feedback. View all current and historical signals in ",
        '<a href="https://data.humdata.org/visualization/signals/">this map</a>.'
      )
    )
  )
}
