box::use(purrr)
box::use(glue)

box::use(./conditional_merge)
box::use(./text_block)

#' Create intro block
#'
#' Create the intro block for the email.
#'
#' @param title Title at the top of the email
#' @param iso3 Vector of ISO3 codes
#' @param location Vector of location names
#' @param summary_short Summary text generated by AI
#' @param use_conditions Whether or not to use conditional merge to
#'      wrap text in Mailchimp conditions for those locations.
#'
#' @returns HTML for intro block
#'
#' @export
add_intro <- function(
    title,
    iso3,
    location,
    summary_short,
    use_conditions = FALSE) {
  # create table of contents manually using jumplinks and conditional text
  toc_items <- purrr$map2_chr(
    .x = glue$glue(
      '<li><p><a href="#{iso3}">{location}</a>: {summary_short}</p></li>'
    ),
    .y = iso3,
    .f = \(x, y) {
      conditional_merge$conditional_merge(
        text = x,
        iso3 = y,
        use_conditions = use_conditions
      )
    }
  )

  # join together with overall text to create the full toc
  toc <- paste0(
    "<ul>",
    paste(toc_items, collapse = ""),
    "</ul>"
  )

  # now just return the intro text block
  text_block$add_text(
    text = toc,
    header = title,
    header_level = 1
  )
}
