box::use(purrr)
box::use(stringr)

box::use(./conditional_merge)
box::use(./text_block)
box::use(./image_block)
box::use(./line_block)
box::use(./summary_block)
box::use(./further_info_block)

#' Create location block
#'
#' Create a location block with information passed in. The only required fields
#' are `iso3` and `location`, although typically all will be passed (even if missing)
#' direct from signals datasets. The `iso3` code is used to generate the conditional
#' merge for MailChimp so the location only appears to interested users.
#'
#' @param iso3 ISO3 code
#' @param location Location name, used for header of section
#' @param plot_title Plot title, used as alt text for plot
#' @param plot_url URL to plot to include
#' @param map_title Map title, used as alt text for plot
#' @param map_url URL to map to include
#' @param plot2_title Plot2 title, used as alt text for plot
#' @param plot2_url URL to plot2 to include
#' @param other_images_urls List of other images to include, separated by ;
#' @param other_images_captions List of other images captions, separated by ;
#' @param summary_long Summary text generated by AI
#' @param summary_source Source of summary text generated by AI
#' @param further_information Further information text
#' @param use_conditions Whether or not to use conditional merge to
#'      wrap text in Mailchimp conditions for those locations.
#'
#' @returns HTML for location block
#'
#' @export
add_location <- function(
    iso3,
    location,
    plot_title = "",
    plot_url = "",
    map_title = "",
    map_url = "",
    plot2_title = "",
    plot2_url = "",
    other_images_urls = "",
    other_images_captions = "",
    summary_long = "",
    summary_source = "",
    further_information = "",
    use_conditions = FALSE) {
  paste0(
    text_block$add_text(header = location, header_level = 2, header_id = iso3),
    image_block$add_image(src = plot_url, alt = plot_title),
    image_block$add_image(src = map_url, alt = map_title),
    image_block$add_image(src = plot2_url, alt = plot2_title),
    purrr$map2_chr(
      .x = stringr$str_split(other_images_urls, ";"),
      .y = stringr$str_split(other_images_captions, ";"),
      .f = \(src, caption) image_block$add_image(src = src, caption = caption)
    ),
    further_info_block$add_further_info(text = further_information),
    summary_block$add_summary(text = summary_long, source = summary_source)
  ) |>
    conditional_merge$conditional_merge(
      iso3 = iso3,
      use_conditions = use_conditions
    )
}
