box::use(glue)

box::use(./text_block)
box::use(./missing[missing_text])

#' Summary block
#'
#' Creates summary block using `text` and generic headers and text.
#'
#' @param text Summary text
#'
#' @export
add_summary <- function(text, source) {
  if (missing_text(text)) {
    ""
  } else {
    caveat <- glue$glue(
      '<em><span style="font-size: 14px">The text below and headline summary was ',
      'generated by the OpenAI</span></em><a href="https://openai.com/index/hello-gpt-4o/">',
      '<em><span style="font-size: 14px"> GPT-4o model</span></em></a><em>',
      '<span style="font-size: 14px">, summarizing information from {source}. ',
      "Read with caution, and follow up with the source links and dataset provided.</span></em>"
    )

    text_block$add_text(
      text = caveat,
      header = "Situation summary",
      header_level = 3,
      pre_header_text = caveat,
      background_color = "#ebebeb"
    )
  }
}
