box::use(./boxed_text_block)
box::use(./text_block)
box::use(./missing[missing_text])

#' Summary block
#'
#' Creates summary block using `text` and generic headers and text.
#'
#' @param text Summary text
#'
#' @export
add_summary <- function(text) {
  if (missing_text(text)) {
    ""
  } else {
    block_box_text <- paste(
      "Context is experimentally generated by the",
      '<a href="https://platform.openai.com/docs/models/gpt-4-turbo-and-gpt-4">OpenAI GPT-4 turbo</a>',
      "model, use with caution."
    )

    paste0(
      text_block$add_text(header = "Situation summary", header_level = 4, header_class = "null"),
      boxed_text_block$add_boxed_text(block_box_text),
      text_block$add_text(text = text)
    )
  }
}
