box::use(glue)

box::use(src/email/components/text_block)
box::use(src/email/components/line_block)
box::use(src/email/components/missing)

#' Summary block
#'
#' Creates summary block using `text` and generic headers and text.
#'
#' @param text Summary text
#'
#' @export
add_summary <- function(text, source) {
  if (missing$missing_text(text)) {
    line_block$add_line() # need line to break up country blocks if no summary
  } else {
    caveat <- glue$glue(
      '<em><span style="font-size: 14px">The text below and introductory headlines were ',
      'generated by the OpenAI</span></em><a href="https://openai.com/index/hello-gpt-4o/">',
      '<em><span style="font-size: 14px"> GPT-4o model</span></em></a><em>',
      '<span style="font-size: 14px">, summarizing information from {source}. ',
      "Read with caution.</span></em>"
    )

    text_block$add_text(
      text = text,
      header = "Situation summary",
      header_level = 3,
      pre_header_text = caveat,
      background_color = "#ebebeb"
    )
  }
}
