box::use(glue)

box::use(./missing[missing_text])

#' Add text block
#'
#' Add text block in the Mailchimp template style. Can pass in the body of
#' text, the header text, and the level of the header
#'
#' @param text Body of text to add. If missing, text div removed.
#' @param header Header text. If missing, header block removed.
#' @param header_level Level of the header, as a number. Corresponds to h1 to h6.
#' @param header_title Boolean. If `TRUE`, gives the header class of `title` so it
#'     appears in table of contents generated by Mailchimp.
#'
#' @returns Full text block HTML
#'
#' @export
add_text <- function(text = "", header = "", header_level = 2, header_class = "title") {
  if (missing_text(text) && missing_text(header)) {
    ""
  } else {
    glue$glue(
      '<table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnTextBlock" style="min-width:100%;">
    <tbody class="mcnTextBlockOuter">
        <tr>
            <td valign="top" class="mcnTextBlockInner" style="padding-top:9px;">
              	<!--[if mso]>
				<table align="left" border="0" cellspacing="0" cellpadding="0" width="100%" style="width:100%;">
				<tr>
				<![endif]-->

				<!--[if mso]>
				<td valign="top" width="600" style="width:600px;">
				<![endif]-->
                <table align="left" border="0" cellpadding="0" cellspacing="0" style="max-width:100%; min-width:100%;" width="100%" class="mcnTextContentContainer">
                    <tbody><tr>

                        <td valign="top" class="mcnTextContent" style="padding: 0px 18px 9px; font-size: 16px; line-height: 150%;">

                            {conditional_header(header, header_level, header_class)}

                            {conditional_text(text)}

                        </td>
                    </tr>
                </tbody></table>
				<!--[if mso]>
				</td>
				<![endif]-->

				<!--[if mso]>
				</tr>
				</table>
				<![endif]-->
            </td>
        </tr>
    </tbody>
</table>'
    )
  }
}

#' Drop header block if doesn't exist
conditional_header <- function(header, header_level, header_class) {
  if (missing_text(header)) {
    ""
  } else {
    glue$glue('"<h{header_level} class="{header_class}">{header}</h{header_level}>"')
  }
}

#' Drop text block if doesn't exist
conditional_text <- function(text) {
  if (missing_text(text)) {
    ""
  } else {
    glue$glue("<div>{text}</div>")
  }
}
