box::use(
  readr,
  utils
)

box::use(src/utils/get_env[get_env])

#' Download raw cholera data
#'
#' Downloads raw cholera data from CERF's GitHub, generated by them scraping
#' PDFs of WHO AFRO health bulletins.
#'
#' @export
raw <- function() {
  # download from the GitHub scraping of CERF
  f <- tempfile(fileext = ".csv")
  utils$download.file(
    url = get_env("CERF_CHOLERA_DATA"),
    destfile = f,
    quiet = TRUE
  )

  readr$read_csv(
    f,
    col_types = readr$cols(.default = "c")
  )
}
