---
title: "email"
output: blastula::blastula_email
---


## <a name="`r country_id`"></a> `r country`

```{r, include=FALSE}
# check if we show a table at the bottom. currently only for the IDMC
show_table <- flag_source == "idmc"

if (flag_source == "idmc") {
  df_idmc_raw <- cs$read_gcs_file("output/idmc/raw.parquet")
  df_display <- df_idmc_raw |>
    dplyr$filter(
      iso3 == !!iso3,
      displacement_end_date >= !!start_date,
      displacement_start_date <= !!end_date
    ) |> 
    dplyr$distinct(
      event_url, event_name
    ) |>
    dplyr$filter(
      !is.na(event_url)
    ) |> 
    dplyr$transmute(
      Reports = paste0(
        "<a href=\"",
        event_url,
        "\">",
        event_name,
        "</a>"
      )
    )
  
  print(df_display)
  
  show_idmc <- show_table & nrow(df_display) > 0
}

# check if we present a text summarization
# not used for the cholera alerts
print_summary <- flag_type != "cholera" & !is.na(summary_experimental)
```

```{r, results = "asis"}
cat(message)
```

```{r, results = "asis"}
p <- plot_general(flag_type, iso3)

email$add_ggplot_custom(
  plot_object = p,
  alt = "Alert plot",
  height = 3,
  width = 6,
  html_width = 1000
)
```

```{r summary_print, child = "summary.Rmd", eval = print_summary}
```

### Further information:

```{r, results = "asis", out.width = "80%"}
if (flag_type == "displacement") {
  cat(
    paste0(
      "Refer to the [IDMC country page](",
      url,
      ") for additional context on displacement, and the [IDMC data ",
      "portal](https://www.internal-displacement.org/database/displacement-data) ",
      "for relevant displacement data.\n\n",
      "IDMC identified displacement events for this alert from the below reports."
    )
  )
} else if (flag_type == "food_insecurity") {
  cat(
    paste0(
      "Refer to the [latest IPC/CH report](",
      url,
      "). Additional information is available on the [IPC website](https://www.ipcinfo.org)."
    )
  )
} else if (flag_type == "cholera") {
  cat(
    paste0(
      "All cholera data derived from ",
      "[WHO AFRO bulletins,",
      "](https://www.afro.who.int/health-topics/disease-outbreaks/outbreaks-and-other-emergencies-updates).",
      " Refer to the bulletins for full context on this alert."
    )
  )
}
```

```{r, eval = show_table}
if (flag_source == "idmc") {
  # load idmc data
  knitr$kable(
    df_display,
    table.attr = "class=\"scrollable\"",
    format = "html",
    escape = FALSE
    )
}
```

----

