box::use(dplyr)

box::use(
  cs = src/utils/cloud_storage,
  src/utils/push_hdx
)

df_dictionary <- dplyr$tribble(
  ~column, ~description,
  "iso3", paste0(
    "ISO3 code for the location. Most are official ISO3 codes, but some custom codes are used. ",
    "See the hdx_signals_location_metadata.csv file for details."
  ),
  "location", "Name of the location.",
  "region", "Name of the region, based on the UNOCHA operational regions.",
  "hrp_location", "Logical column indicating if it is currently an HRP location.",
  "indicator_id", "ID for the indicator the signal was generated from.",
  "date", paste0(
    "Date in the dataset when a signal was detected. This corresponds to when ",
    "thresholds for the indicator_id have been passed based on dates in the source ",
    "dataset. See `campaign_date` for date that a signal was actually generated."
  ),
  "alert_level", paste0(
    "Level of concern for the generated signal, either medium or high concern. ",
    "Signals are only generated if there was no signal at that level of concern ",
    "or higher detected in the past 6 months."
  ),
  "value", paste0(
    "Indicator value that was detected and generated the signal. For instance, internal ",
    "displacements in the past month or hotspot classification level for JRC agricultural ",
    "hotspots. See methodology page for more details."
  ),
  "plot", "URL to the plot used in the email campaign, if any.",
  "map", "URL to the map used in the email campaign, if any.",
  "plot2", "URL to the additional plot used in the email campaign, if any.",
  "other_images", "URL to any other images used in the email campaign, if any.",
  "summary_long", paste0(
    "Situation summary generated by AI used in the location blocks in the email ",
    "campaigns. Only generated if sufficient text data is available to pass for .",
    "summarization."
  ),
  "summary_short", "Short headline summary used for the intro of the email campaign.",
  "summary_source", "Source of the information used for text summarization.",
  "hdx_url", "URL to the HDX dataset where the signal was detected.",
  "source_url", "Primary source URL for the information in the email campaign.",
  "other_urls", "Additional source URLs linked in the email campaign.",
  "further_information", "Text used in the `Further information` section of the email campaign.",
  "campaign_url", "URL to the full email campaign.",
  "campaign_date", "Date that the email campaign was actually generated.",
  "signals_version", "Version of the Signals code used to generate the signal."
)

cs$update_az_file(
  df = df_dictionary,
  name = "output/hdx_signals_data_dictionary.csv"
)

push_hdx$push_hdx()
