#' Script to set the start dates for IDMC time series. IDMC data is not consistent
#' across time, and IDMC does not currently provide a dataset indicating when
#' time series begin, so we manually set if and when necessary.
box::use(
  dplyr,
  knitr,
  logger,
  stringr
)

box::use(
  cs = src/utils/cloud_storage
)

df_dates <- dplyr$tribble(
  ~iso3, ~displacement_type, ~start_date,
  "SOM", "Conflict", "2022-09-01"
) |>
  dplyr$mutate(
    start_date = as.Date(start_date)
  )

# save dataset

fname <- "input/idmc_dates.parquet"
cs$update_az_file(
  df = df_dates,
  name = fname
)

logger$log_info(paste0("Successfully updated IDMC dates and saved to ", fname))

# save markdown file

md_table <- df_dates |>
  dplyr$mutate(
    start_date = format(start_date, "%B %e %Y") |>
      stringr$str_replace_all("  ", " ")
  ) |>
  knitr$kable(
    format = "markdown"
  ) |>
  paste(
    collapse = "\n"
  )

explanation <- paste(
  "IDMC time series are not always consistent in coverage. Until the IDMC provides",
  "coverage data similar to ACLED, we manually set the start date for analysis",
  "if a time series appears unlikely."
)

paste(
  "[comment]: <> (This file is autogenerated, do not edit. Edit publish_prompts.R directly.)",
  "## IDMC coverage",
  explanation,
  md_table,
  sep = "\n\n"
) |>
  writeLines(
    file.path(
      "docs",
      "datasets",
      "displacement-dates.md"
    )
  )

logger$log_info(paste0("Successfully updated IDMC dates and saved to ", fname))
