#' Extracts prompts from text files into documentation
box::use(stringr)
box::use(purrr)

prompts <- list.files(
  path = "src/indicators",
  pattern = "\\.txt$",
  recursive = TRUE,
  full.names = TRUE
)

# get the indicators that we have prompts for
indicators <- prompts |>
  stringr$str_extract("(?<=indicators\\/)(.*)(?=\\/prompts)")

indicators_unique <- unique(indicators)

# intro to the text
intro <- paste(
  "# AI summarization\n",
  "For datasets where text information is publicly available, OpenAI's",
  "[GPT-4o large language model](https://openai.com/index/hello-gpt-4o/)",
  "is used to generate summary content for signals, to provide additional",
  "context to the quantitative data and visualizations generated by the",
  "system. Publicly available text data from primary datasets and linked",
  "secondary sources is aggregated and passed to GPT-4o to produce key",
  "headlines (short summaries) and situation summaries (long summaries) for",
  "each signal.\n\n",
  "Refer to the `src/indicators` source code to see what information is passed",
  "to the AI for summarization.",
  "Below you can find the prompts passed to GPT-4o to generate the summary text.",
  collapse = "\n"
)

# get list of indicators that includes links to anchors generated later
indicators_list <- paste0(
  paste0(
    "- [",
    indicators_unique,
    "](#",
    indicators_unique,
    ")",
    collapse = "\n"
  ),
  "\n",
  sep = "\n"
)

# generate the sections for each indicator by adding the
prompt_section <- purrr$map_chr(
  .x = indicators_unique,
  .f = \(ind) {
    ind_title <- paste0(
      "### ",
      ind,
      "<a name='",
      ind,
      "'></a>"
    )

    # get all actual prompts from the data
    ind_index <- indicators == ind
    prompt_txt <- purrr$map_chr(
      .x = prompts[ind_index],
      .f = \(prompt) {
        paste0(
          "#### ",
          basename(prompt),
          "\n\n",
          paste0(
            "> ",
            readLines(prompt),
            collapse = "\n"
          )
        )
      }
    ) |>
      paste(collapse = "\n\n")

    paste(
      ind_title,
      prompt_txt,
      sep = "\n\n",
      collapse = "\n\n"
    )
  }
) |>
  paste(collapse = "\n\n")

# generate the final markdown file

paste(
  "[comment]: <> (This file is autogenerated, do not edit. Edit publish_prompts.R directly.)\n",
  intro,
  indicators_list,
  prompt_section,
  sep = "\n"
) |>
  writeLines(
    file.path(
      "docs",
      "PROMPTS.md"
    )
  )
