library(idmc)
library(tidyverse)
library(lubridate)
library(openai)

source(
  file.path(
    "src",
    "utils",
    "get_country_names.R"
  )
)

source(
  file.path(
    "src",
    "utils",
    "format_date.R"
  )
)

# authorize and prep
source(
  file.path(
    "src",
    "utils",
    "google_sheets.R"
  )
)

source(
  file.path(
    "src",
    "utils",
    "flagging.R"
  )
)

##############################
#### DRIVE AND LOCAL DATA ####
##############################

# country links on the IDMC page
df_links <- read_gs_file("idmc_country_links")

##############
#### IDMC ####
##############

df_idmc_raw <- idmc_get_data() %>%
  filter(
    displacement_type == "Conflict"
  )

df_idmc <- df_idmc_raw %>%
  idmc_transform_daily() %>%
  select(
    iso3,
    date,
    displacement_daily
  ) %>%
  group_by(
    iso3
  )

# calculate the flags using the utilities functions
df_flagged <- calculate_flags(
  .data = df_idmc,
  date = 1,
  x = displacement_daily,
  first_since = c(180, 365),
  periods = c(7, 30, 90, 365),
  thresholds_pcts = 0.95,
  thresholds_static = c(5000, 25000, 100000, 500000),
  thresholds_minimums = c(1000, 5000, 10000, 25000)
)

df_idmc_flags <- wrangle_alerts(
  df_flagged,
  date,
  displacement_daily
) %>%
  left_join(
    df_links,
    by = "iso3"
  ) %>%
  transmute(
    iso3,
    flag_type = "displacement",
    flag_source = "idmc",
    start_date = alert_start_date,
    end_date = alert_end_date,
    latest_flag = case_when(
      alert_name == "flag_first_180" ~ "1st_6_months",
      alert_name == "flag_first_365" ~ "1st_year",
      alert_name == "flag_anomaly_7" ~ "weekly",
      alert_name == "flag_anomaly_30" ~ "monthly",
      alert_name == "flag_anomaly_180" ~ "quarterly",
      alert_name == "flag_anomaly_365" ~ "yearly"
    ),
    message_date = case_when(
      data_end_date - data_start_date == 0 ~ paste("on", format_date(data_end_date)),
      year(data_end_date) == year(data_start_date) ~ paste("between", format_date(data_start_date), "and", format_date(data_end_date)),
      TRUE ~ paste("between", format_date(data_start_date), "and", format_date(data_end_date))
    ),
    message = paste0(
      scales::comma(round(data_sum)),
      " people were displaced ",
      message_date,
      "."
    ),
    url = paste0("https://www.internal-displacement.org/countries/", country_link)
  ) %>%
  select(
    -message_date
  )

#####################################
#### COMPARE WITH EXISTING FILES ####
#####################################

df_idmc_flags_prev <- read_gs_file("flags_idmc") %>%
  mutate(
    email = FALSE
  )

# all these new data will need new summaries generated by GPT
# which can include not new alerts (where the start date is the same,
# but a later end date because new data has been added)
df_idmc_flags_new <- anti_join(
  df_idmc_flags,
  df_idmc_flags_prev,
  by = c("iso3", "start_date", "end_date")
) %>%
  left_join(
    select(
      df_idmc_flags_prev,
      iso3,
      start_date,
      email
    ),
    by = c("iso3", "start_date")
  ) %>%
  group_by(iso3) %>%
  mutate(
    email = ifelse(
      Sys.Date() - end_date > 60 | start_date != max(start_date), # do not email for old events updated or if not the latest alert
      FALSE,
      replace_na(email, TRUE) # create emails for new alerts
    )
  ) %>%
  ungroup()

#######################
#### GPT EXPLAINER ####
#######################

df_explain <- df_idmc_flags_new %>%
  select(
    iso3, start_date, end_date, message
  )

ai_summary <- pmap_chr(
  df_explain,
  \(iso3, start_date, end_date, message) {
    # get all reports of displacement
    df_filtered <- df_idmc_raw %>%
      filter(
        iso3 == !!iso3,
        displacement_end_date >= !!start_date,
        displacement_start_date <= !!end_date
      )

    reports <- df_filtered$event_info

    # concat into input
    displacement_info <- paste(
      reports,
      collapse = "\n"
    )

    # random sample reports to ensure token length not problem for OpenAI
    while (nchar(displacement_info) > 3800) {
      reports <- reports[-sample(seq_along(reports), size = 1)]
      displacement_info <- paste(reports, collapse = "\n")
    }

    # get AI summarization
    req <- paste0(
      message,
      ". This information comes from a series of small reports. ",
      "In a short paragraph, please summarize the main reasons for displacement. ",
      "Avoid providing specific numbers or dates, just provide the general ",
      "reasons behind the displacement and other key qualitative information. ",
      "Only use the below information: ",
      displacement_info
    )

    # get AI summarization
    insistent_ai <- insistently(
      \(req) {
        create_completion(
          model = "text-davinci-003",
          prompt = req,
          max_tokens = 100
        )$choices$text
      },
      rate = rate_delay(pause = 3, max_times = 5)
    )

    insistent_ai(req)
  },
  .progress = TRUE
)

df_idmc_flags_new$summary_experimental <- str_remove_all(ai_summary, "\\\n")

#################################
#### CREATE FINAL FLAGS FILE ####
#################################

# create the final flag set by pulling in the previous summaries
# for flag rows that are not new anymore

df_idmc_flags_final <- df_idmc_flags_new %>%
  bind_rows(
    inner_join(
      df_idmc_flags,
      select(
        df_idmc_flag_prev,
        iso3,
        start_date,
        end_date,
        email,
        summary_experimental
      ),
      by = c("iso3", "start_date", "end_date")
    )
  ) %>%
  get_country_names()

########################
#### SAVE IDMC DATA ####
########################

update_gs_file(
  df = get_country_names(df_idmc_raw),
  name = "raw_idmc"
)

update_gs_file(
  df = get_country_names(df_idmc),
  name = "wrangled_idmc"
)

update_gs_file(
  df = df_idmc_flags_final,
  name = "flags_idmc"
)
