# external packages
box::use(idmc)
box::use(dplyr)
box::use(lubridate)
box::use(purrr)
box::use(rlang[`!!`])
box::use(tidyr)

# internal utilities
# first set the root search path for utilities
box::use(gs = ../../utils/google_sheets)
box::use(../../utils/ai_summarizer[ai_summarizer])
box::use(../../utils/get_country_names[get_country_names])
box::use(../../utils/format_date[format_date])
box::use(../../utils/flagging)

##############################
#### DRIVE AND LOCAL DATA ####
##############################

# country links on the IDMC page
df_links <- gs$read_gs_file("idmc_country_links")

##############
#### IDMC ####
##############

df_idmc_raw <- idmc$idmc_get_data() |>
  dplyr$filter(
    displacement_type == "Conflict"
  )

df_idmc <- df_idmc_raw |>
  idmc$idmc_transform_daily() |>
  dplyr$select(
    iso3,
    date,
    displacement_daily
  ) |>
  dplyr$group_by(
    iso3
  )

# calculate the flags using the utilities functions
df_flagged <- flagging$calculate_flags(
  .data = df_idmc,
  x_col = "displacement_daily",
  first_since = c(180, 365),
  periods = c(7, 30, 90, 365),
  thresholds_pcts = 0.95,
  thresholds_static = c(5000, 25000, 100000, 500000),
  thresholds_minimums = c(1000, 5000, 10000, 25000)
)

df_idmc_flags <- flagging$generate_alerts(
  .data = df_flagged,
  date_col = "date",
  x_col = "displacement_daily"
) |>
  dplyr$left_join(
    df_links,
    by = "iso3"
  )  |>
  dplyr$transmute(
    iso3,
    flag_type = "displacement",
    flag_source = "idmc",
    start_date = alert_start_date,
    end_date = alert_end_date,
    latest_flag = dplyr$case_when(
      alert_name == "flag_first_180" ~ "1st_6_months",
      alert_name == "flag_first_365" ~ "1st_year",
      alert_name == "flag_anomaly_7" ~ "weekly",
      alert_name == "flag_anomaly_30" ~ "monthly",
      alert_name == "flag_anomaly_90" ~ "quarterly",
      alert_name == "flag_anomaly_365" ~ "yearly"
    ),
    message_date = dplyr$case_when(
      data_end_date - data_start_date == 0 ~ paste("on", format_date(data_end_date)),
      lubridate$year(data_end_date) == lubridate$year(data_start_date) ~ paste("between", format_date(data_start_date), "and", format_date(data_end_date)),
      TRUE ~ paste("between", format_date(data_start_date), "and", format_date(data_end_date))
    ),
    message = paste0(
      scales::comma(round(data_sum)),
      " people were displaced ",
      message_date,
      "."
    ),
    url = paste0("https://www.internal-displacement.org/countries/", country_link)
  ) |>
  dplyr$select(
    -message_date
  )

#####################################
#### COMPARE WITH EXISTING FILES ####
#####################################

df_idmc_flags_prev <- gs$read_gs_file("flags_idmc") |>
  dplyr$mutate(
    email = FALSE
  )

# all these new data will need new summaries generated by GPT
# which can include not new alerts (where the start date is the same,
# but a later end date because new data has been added)
df_idmc_flags_new <- dplyr$anti_join(
  df_idmc_flags,
  df_idmc_flags_prev,
  by = c("iso3", "start_date", "end_date")
) |>
  dplyr$left_join(
    dplyr$select(
      df_idmc_flags_prev,
      iso3,
      start_date,
      email
    ),
    by = c("iso3", "start_date")
  ) |>
  dplyr$group_by(iso3) |>
  dplyr$mutate(
    email = ifelse(
      Sys.Date() - end_date > 60 | start_date != max(start_date), # do not email for old events updated or if not the latest alert
      FALSE,
      tidyr$replace_na(email, TRUE) # create emails for new alerts
    )
  ) |>
  dplyr$ungroup()

#######################
#### GPT EXPLAINER ####
#######################

df_explain <- df_idmc_flags_new |>
  dplyr$select(
    iso3, start_date, end_date, message
  )

df_idmc_flags_new$summary_experimental <- purrr$pmap_chr(
  df_explain,
  \(iso3, start_date, end_date, message) {
    # get all reports of displacement
    df_filtered <- df_idmc_raw |>
      dplyr$filter(
        iso3 == !!iso3,
        displacement_end_date >= !!start_date,
        displacement_start_date <= !!end_date
      )

    reports <- df_filtered$event_info[!is.na(df_filtered$event_info)]

    # get AI summarization
    prompt <- paste(
      message,
      "This information comes from a series of small reports.",
      "In a short paragraph, please summarize the main reasons for displacement.",
      "Avoid providing specific numbers or dates, just provide the general",
      "reasons behind the displacement and other key qualitative information.",
      "Only use the below information:"
    )

    # get AI summarization
    ai_summarizer(
      prompt = prompt,
      info = reports
    )
  },
  .progress = TRUE
)

#################################
#### CREATE FINAL FLAGS FILE ####
#################################

# create the final flag set by pulling in the previous summaries
# for flag rows that are not new anymore

df_idmc_flags_final <- df_idmc_flags_new |>
  dplyr$bind_rows(
    dplyr$inner_join(
      df_idmc_flags,
      dplyr$select(
        df_idmc_flags_prev,
        iso3,
        start_date,
        end_date,
        email,
        summary_experimental
      ),
      by = c("iso3", "start_date", "end_date")
    )
  ) |>
  get_country_names()

########################
#### SAVE IDMC DATA ####
########################

gs$update_gs_file(
  df = get_country_names(df_idmc_raw),
  name = "raw_idmc"
)

gs$update_gs_file(
  df = get_country_names(df_flagged),
  name = "wrangled_idmc"
)

gs$update_gs_file(
  df = df_idmc_flags_final,
  name = "flags_idmc"
)
