box::use(readr)

#' Download raw cholera data
#'
#' Downloads raw cholera data from CERF's GitHub, generated by them scraping
#' PDFs of WHO AFRO health bulletins.
#'
#' @export
raw <- function() {
  # download from the GitHub scraping of CERF
  f <- tempfile(fileext = ".csv")
  download.file(
    url = Sys.getenv("CERF_CHOLERA_DATA"),
    destfile = f
  )

  readr$read_csv(
    f,
    col_types = readr$cols(.default = "c")
  )
}
