# this workflow checks the CHANGES.md file

on:
  pull_request:
    branches: [main]

name: Check CHANGES.md

permissions: read-all

jobs:
  check-changes:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Install R
            uses: r-lib/actions/setup-r@v2

          - name: Cache R dependencies
            id: cache-r-deps
            uses: actions/cache@v2
            with:
              path: ${{ env.R_LIBS_USER }}
              key: R-dependency-cache-${{ hashFiles('.github/workflows/check_changes.yml') }}

          - name: Install dependencies
            shell: Rscript {0}
            if: steps.cache-r-deps.outputs.cache-hit != 'true'
            run: install.packages(c("box", "stringr"))

          - name: Check CHANGES.md
            shell: bash
            run: Rscript ./src/repo/check_changes.R
