# This workflow uses actions to automatically run the global monitoring
# script.

name: global-monitoring

on:
  workflow_dispatch:
    inputs:
      test_run:
        required: true
        type: choice
        default: "TRUE"
        options:
          - "TRUE"
          - "FALSE"
#  schedule:
#    - cron: "0 11 * * 1-5"

jobs:
  monitor:
    runs-on: ubuntu-latest
    env:
      RENV_PATHS_ROOT: ~/.cache/R/renv
      IDMC_API: ${{ secrets.IDMC_API }}
      IPC_API_KEY: ${{ secrets.IPC_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GLOBAL_MONITORING_JSON: "auth.json"
      CHD_DS_EMAIL_USERNAME: ${{ secrets.CHD_DS_EMAIL_USERNAME }}
      CHD_DS_EMAIL_PASSWORD: ${{ secrets.CHD_DS_EMAIL_PASSWORD }}
      CHD_DS_EMAIL_ADDRESS: ${{ secrets.CHD_DS_EMAIL_ADDRESS }}
      CHD_DS_HOST: ${{ secrets.CHD_DS_HOST }}
      CHD_DS_PORT: ${{ secrets.CHD_DS_PORT }}
      CERF_CHOLERA_DATA: ${{ secrets.CERF_CHOLERA_DATA }}
      GMAS_TEST_RUN: ${{ inputs.test_run || 'FALSE' }}

    steps:
      - uses: actions/checkout@v3
      - name: Install required dependencies
      # Solution to unstable Azure server access is to update apt-get
      # Found on: https://github.com/actions/runner-images/issues/675
        run: |
          sudo apt-get update
          sudo apt-get install -y -f libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libudunits2-dev libgdal-dev
      - name: Set up R 4.2.3
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.2.3
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Cache packages
        uses: actions/cache@v3
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      - name: Restore packages
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
        shell: Rscript {0}
      - name: Create authorization JSON
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "auth.json"
          json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Update source indicators
        run: |
          find src/indicators -name "update_*.R" -exec Rscript {} \;
        shell: bash
      - name: Update flags and send emails
        run: |
          Rscript src/send_alerts.R
        shell: bash
