# This workflow uses actions to automatically run the global monitoring
# script.

name: global-monitoring

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    env:
      RENV_PATHS_ROOT: ~/Library/Caches/org.R-project.R/R/renv
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up R 4.2.3
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: 4.2.3
      - name: Cache packages
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      - name: Restore packages
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
        shell: Rscript {0}
      - name: Create authorization JSON
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "auth.json"
          json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Create R environment from GitHub secrets
        run: |
          echo IDMC_API="$IDMC_API" >> ~/.Renviron
          echo IPC_API_KEY="$IPC_API_KEY" >> ~/.Renviron
          echo OPENAI_API_KEY="$OPENAI_API_KEY" >> ~/.Renviron
          echo GLOBAL_MONITORING_JSON="auth.json" >> ~/.Renviron
          shell: bash
      - name: Run global monitoring
        run: |
          source(file.path("src", "run.R"))
        shell: Rscript {0}