# this workflow lints the repository

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: Lint

permissions: read-all

jobs:
  lint:
      runs-on: ubuntu-latest
      env:
      steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Set up environment
            uses: ocha-dap/hdx-signals-actions@v3

          - name: Install extra dependencies
            shell: Rscript {0}
            run: install.packages(c("lintr", "box.linters"))

          - name: Lint
            run: lintr::lint_dir()
            shell: Rscript {0}
            env:
              LINTR_ERROR_ON_LINT: true
