# this workflow lints the repository

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: Lint

permissions: read-all

jobs:
  lint:
      runs-on: ubuntu-latest
      env:
          HS_EMAIL: ${{ secrets.HS_EMAIL}}
          HS_SURVEY_LINK: ${{ secrets.HS_SURVEY_LINK}}
          IPC_API_KEY: ${{ secrets.IPC_API_KEY }}
          IDMC_API: ${{ secrets.IDMC_API }}
          ACLED_ACCESS_KEY: ${{ secrets.ACLED_ACCESS_KEY }}
          ACLED_EMAIL_ADDRESS: ${{ secrets.ACLED_EMAIL_ADDRESS }}
          CERF_CHOLERA_DATA: ${{ secrets.CERF_CHOLERA_DATA }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DSCI_AZ_SAS_DEV: ${{ secrets.DSCI_AZ_SAS_DEV }}
          DSCI_AZ_SAS_PROD: ${{ secrets.DSCI_AZ_SAS_PROD }}
          MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY }}
          HS_LOCAL: ${{ inputs.HS_LOCAL || 'FALSE' }}
          HS_FIRST_RUN: ${{ inputs.HS_FIRST_RUN || 'FALSE' }}
          HS_DRY_RUN: ${{ inputs.HS_DRY_RUN || 'FALSE' }}
          LOG_LEVEL: ${{ inputs.LOG_LEVEL || 'DEBUG' }}
      steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Set up environment
            uses: ocha-dap/hdx-signals-actions@v3

          - name: Install extra dependencies
            shell: Rscript {0}
            run: install.packages(c("lintr", "box.linters"))

          - name: Lint
            run: lintr::lint_dir()
            shell: Rscript {0}
            env:
              LINTR_ERROR_ON_LINT: true
