name: Monitor IDMC displacement disaster

on:
    workflow_dispatch:
      inputs:
        HS_FIRST_RUN:
          required: true
          type: choice
          default: "FALSE"
          options:
            - "TRUE"
            - "FALSE"
        HS_DRY_RUN:
          required: true
          type: choice
          default: "TRUE"
          options:
            - "TRUE"
            - "FALSE"
        HS_LOCAL:
          required: true
          type: choice
          default: "TRUE"
          options:
            - "TRUE"
            - "FALSE"
        LOG_LEVEL:
          required: true
          type: choice
          default: "DEBUG"
          options:
            - "DEBUG"
            - "INFO"
            - "WARNING"
            - "ERROR"
    schedule:
      - cron: "0 8 * * 1-5"

jobs:
    run:
        runs-on: ubuntu-latest
        env:
          HS_EMAIL: ${{ secrets.HS_EMAIL}}
          HS_SURVEY_LINK: ${{ secrets.HS_SURVEY_LINK}}
          IDMC_API: ${{ secrets.IDMC_API }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DSCI_AZ_BLOB_DEV_SAS: ${{ secrets.DSCI_AZ_BLOB_DEV_SAS }}
          DSCI_AZ_BLOB_PROD_SAS: ${{ secrets.DSCI_AZ_BLOB_PROD_SAS }}
          MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY }}
          HS_LOCAL: ${{ inputs.HS_LOCAL || 'FALSE' }}
          HS_FIRST_RUN: ${{ inputs.HS_FIRST_RUN || 'FALSE' }}
          HS_DRY_RUN: ${{ inputs.HS_DRY_RUN || 'FALSE' }}
          LOG_LEVEL: ${{ inputs.LOG_LEVEL || 'INFO' }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up environment
              uses: ocha-dap/hdx-signals-actions@v3

            - name: Run R monitoring script
              uses: nick-fields/retry@v3
              with:
                max_attempts: 2
                timeout_minutes: 20
                retry_on: error
                retry_wait_seconds: 120
                shell: bash
                command: Rscript ./src/indicators/idmc_displacement/disaster/__init__.R
