name: Monitor ACLED conflict

on:
    workflow_dispatch:
      inputs:
        HS_FIRST_RUN:
          required: true
          type: choice
          default: "FALSE"
          options:
            - "TRUE"
            - "FALSE"
        HS_DRY_RUN:
          required: true
          type: choice
          default: "TRUE"
          options:
            - "TRUE"
            - "FALSE"
        HS_LOCAL:
          required: true
          type: choice
          default: "TRUE"
          options:
            - "TRUE"
            - "FALSE"
        LOG_LEVEL:
          required: true
          type: choice
          default: "DEBUG"
          options:
            - "DEBUG"
            - "INFO"
            - "WARNING"
            - "ERROR"
    schedule:
      - cron: "0 8 * * 1-5"

jobs:
    run:
        runs-on: ubuntu-latest
        env:
          HS_EMAIL: ${{ secrets.HS_EMAIL}}
          HS_SURVEY_LINK: ${{ secrets.HS_SURVEY_LINK}}
          ACLED_USERNAME: ${{ secrets.ACLED_USERNAME }}
          ACLED_PASSWORD: ${{ secrets.ACLED_PASSWORD }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DSCI_AZ_BLOB_DEV_SAS_WRITE: ${{ secrets.DSCI_AZ_BLOB_DEV_SAS_WRITE }}
          DSCI_AZ_BLOB_PROD_SAS_WRITE: ${{ secrets.DSCI_AZ_BLOB_PROD_SAS_WRITE }}
          MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY }}
          HS_LOCAL: ${{ inputs.HS_LOCAL || 'FALSE' }}
          HS_FIRST_RUN: ${{ inputs.HS_FIRST_RUN || 'FALSE' }}
          HS_DRY_RUN: ${{ inputs.HS_DRY_RUN || 'FALSE' }}
          LOG_LEVEL: ${{ inputs.LOG_LEVEL || 'INFO' }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up environment
              uses: ocha-dap/hdx-signals-actions@v3

            - name: Get GitHub Actions IP Address
              run: |
                echo "=== GITHUB ACTIONS IP ADDRESS DETECTION ==="
                echo "This information is to understand what IP address GHA is using"
                echo ""
                echo "Public IP (via ipify.org):"
                curl -s https://api.ipify.org || echo "Failed to get IP from ipify.org"
                echo ""
                echo "Public IP (via httpbin.org):"
                curl -s https://httpbin.org/ip | jq -r '.origin' || echo "Failed to get IP from httpbin.org"
                echo ""
                echo "Public IP (via ifconfig.me):"
                curl -s https://ifconfig.me || echo "Failed to get IP from ifconfig.me"
                echo ""
                echo "Network interface information:"
                ip addr show || ifconfig || echo "Could not get network interface info"
                echo ""
                echo "DNS resolution for acleddata.com:"
                nslookup acleddata.com || dig acleddata.com || echo "Could not resolve acleddata.com"
                echo ""
                echo "Trace route to acleddata.com (first 5 hops):"
                traceroute -m 5 acleddata.com || echo "Traceroute not available"

            - name: Test ACLED OAuth Authentication
              run: |
                echo "=== Testing ACLED OAuth with Enhanced Logging ==="
                echo "This test follows ACLED's exact OAuth documentation"
                Rscript tmp/test_acled_oauth.R

            - name: Run R monitoring script
              uses: nick-fields/retry@v3
              with:
                max_attempts: 2
                timeout_minutes: 20
                retry_on: error
                retry_wait_seconds: 120
                shell: bash
                command: Rscript ./src/indicators/acled_conflict/__init__.R
