name: Monitor ACLED conflict

on:
    workflow_dispatch:
      inputs:
        first_run:
          required: true
          type: choice
          default: "FALSE"
          options:
            - "TRUE"
            - "FALSE"
        test:
          required: true
          type: choice
          default: "TRUE"
          options:
            - "TRUE"
            - "FALSE"
        GMAS_TEST_RUN:
          required: true
          type: choice
          default: "TRUE"
          options:
            - "TRUE"
            - "FALSE"
    # schedule:
    #   - cron: "0 11 * * 2"

jobs:
    run:
        runs-on: ubuntu-latest
        env:
          ACLED_ACCESS_KEY: ${{ secrets.ACLED_ACCESS_KEY }}
          ACLED_EMAIL_ADDRESS: ${{ secrets.ACLED_EMAIL_ADDRESS }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DSCI_AZ_SAS_DEV: ${{ secrets.DSCI_AZ_SAS_DEV }}
          DSCI_AZ_SAS_PROD: ${{ secrets.DSCI_AZ_SAS_PROD }}
          MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY }}
          GMAS_TEST_RUN: ${{ inputs.GMAS_TEST_RUN || 'FALSE' }}
          FIRST_RUN: ${{ inputs.first_run || 'FALSE' }}
          TEST: ${{ inputs.test || 'FALSE' }}
        steps:   
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up environment
              uses: ocha-dap/hdx-signals-actions@07b3181e914ef100bd9c8134f3c7a13383870b9d

            - name: Run R monitoring script
              shell: bash
              run: Rscript ./src/indicators/acled_conflict/update_conflict.R
