name: Post Slack update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 1-5"

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN}}
      DSCI_AZ_SAS_PROD: ${{ secrets.DSCI_AZ_SAS_PROD }}
      HS_SLACK_URL: ${{ secrets.HS_SLACK_URL}}
      MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY }}
      HS_DRY_RUN: ${{ 'FALSE' }}
      HS_LOCAL: ${{ 'FALSE' }}
    steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Set up environment
          uses: ocha-dap/hdx-signals-actions@v3

        - name: Create Slack message
          shell: bash
          run: Rscript ./src/signals/check_signals_updates.R
