# this workflow publishes PROMPTS.md

on:
  pull_request:
    branches: [main]

name: Publish PROMPTS.md when prompts added or changed

permissions: read-all

jobs:
  job-name:
    permissions:
      contents: write
  publish-prompts:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout repository
            uses: actions/checkout@v4
            with:
              ref: ${{ github.event.pull_request.head.ref }} # ensures we can commit

          - name: Check that txt files for prompts have been changed
            uses: dorny/paths-filter@v3
            id: changes
            with:
              filters: |
                src:
                  - 'src/indicators/*/prompts/*.txt'

          - name: Set up environment
            if: steps.changes.outputs.src == 'true'
            uses: ocha-dap/hdx-signals-actions@v2

          - name: Update PROMPTS.md
            if: steps.changes.outputs.src == 'true'
            shell: bash
            run: Rscript ./src/repo/publish_prompts.R

          - name: Commit PROMPTS.md
            if: steps.changes.outputs.src == 'true'
            run: |
              git config user.email "gha@email.com"
              git config user.name "GHA"
              git add docs/PROMPTS.md
              git commit -m "Publish PROMPTS.md"

          - name: Push changes
            if: steps.changes.outputs.src == 'true'
            uses: ad-m/github-push-action@master
            with:
              github_token: ${{ secrets.GH_TOKEN }}
              branch: ${{ github.ref }}
