# this workflow checks the CHANGES.md file

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

name: Test HDX Signals

permissions: read-all

jobs:
  check-changes:
      runs-on: ubuntu-latest
      strategy:
          matrix:
            test-scripts: [
              "src/email/components/__init__.R",
              "src/email/mailchimp/__init__.R",
              "src/utils/__init__.R"
            ]
      steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Set up environment
            uses: ocha-dap/hdx-signals-actions@v3

          - name: Run tests
            shell: bash
            run: Rscript ${{ matrix.test-scripts }}
