# This workflow uses actions to automatically run the global monitoring
# script.

name: test-emails

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    env:
      RENV_PATHS_ROOT: ~/Library/Caches/org.R-project.R/R/renv

    steps:
      - uses: actions/checkout@v3
      - name: Set up R 4.2.3
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: 4.2.3
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Cache packages
        uses: actions/cache@v3
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      - name: Restore packages
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
        shell: Rscript {0}
      - name: Create authorization JSON
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "auth.json"
          json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Run global monitoring
        run: |
          source(file.path("src", "run.R"))
        shell: Rscript {0}
        env:
          GLOBAL_MONITORING_JSON: "auth.json"
          CHD_DS_EMAIL_USERNAME: ${{ secrets.CHD_DS_EMAIL_USERNAME }}
          CHD_DS_EMAIL_PASSWORD: ${{ secrets.CHD_DS_EMAIL_PASSWORD }}
          CHD_DS_HOST: ${{ secrets.CHD_DS_HOST }}
          CHD_DS_PORT: ${{ secrets.CHD_DS_PORT }}
