name: Triage Signals

on:
    workflow_dispatch:
      inputs:
        HS_FIRST_RUN:
          required: true
          type: choice
          default: "FALSE"
          options:
            - "TRUE"
            - "FALSE"
        HS_DRY_RUN:
          required: true
          type: choice
          default: "TRUE"
          options:
            - "TRUE"
            - "FALSE"
        HS_LOCAL:
          required: true
          type: choice
          default: "TRUE"
          options:
            - "TRUE"
            - "FALSE"
        LOG_LEVEL:
          required: true
          type: choice
          default: "DEBUG"
          options:
            - "DEBUG"
            - "INFO"
            - "WARNING"
            - "ERROR"
        USER_COMMAND:
          required: true
          type: choice
          default: "DO_NOTHING"
          options:
            - "DO_NOTHING"
            - "APPROVE"
            - "DELETE"
            - "ARCHIVE"
        USER_COMMAND_CONFIRMATION:
          required: true
          type: choice
          default: "DONT CONFIRM"
          options:
            - "DONT CONFIRM"
            - "I CONFIRM"
jobs:
    run:
        runs-on: ubuntu-latest
        env:
          HS_EMAIL: ${{ secrets.HS_EMAIL}}
          HS_SURVEY_LINK: ${{ secrets.HS_SURVEY_LINK}}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DSCI_AZ_BLOB_DEV_SAS_WRITE: ${{ secrets.DSCI_AZ_BLOB_DEV_SAS_WRITE }}
          DSCI_AZ_BLOB_PROD_SAS_WRITE: ${{ secrets.DSCI_AZ_BLOB_PROD_SAS_WRITE }}
          MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY }}
          HS_LOCAL: ${{ inputs.HS_LOCAL || 'FALSE' }}
          HS_FIRST_RUN: ${{ inputs.HS_FIRST_RUN || 'FALSE' }}
          HS_DRY_RUN: ${{ inputs.HS_DRY_RUN || 'FALSE' }}
          LOG_LEVEL: ${{ inputs.LOG_LEVEL || 'INFO' }}
          USER_COMMAND: ${{ inputs.USER_COMMAND || 'DO_NOTHING'}}
          USER_COMMAND_CONFIRMATION: ${{ inputs.USER_COMMAND_CONFIRMATION || 'I CONFIRM'}}
      steps:
          - name: Checkout repository
            uses: actions/checkout@v3

          - name: Set up environment
            uses: ocha-dap/hdx-signals-actions@v3

          - name: Run R monitoring script
            uses: nick-fields/retry@v3
            with:
              max_attempts: 2
              timeout_minutes: 5
              retry_on: error
              retry_wait_seconds: 120
              shell: bash
              command: Rscript ./src/signals/triage_signals.R
