name: Update locations data

on:
    workflow_dispatch:
      inputs:
        HS_LOCAL:
          required: true
          type: choice
          default: "FALSE"
          options:
            - "TRUE"
            - "FALSE"

jobs:
    run:
        runs-on: ubuntu-latest
        env:
          HS_LOCAL: ${{ inputs.HS_LOCAL || 'FALSE' }}
          HS_HDX_BEARER: ${{ secrets.HS_HDX_BEARER }}
          DSCI_AZ_SAS_DEV: ${{ secrets.DSCI_AZ_SAS_DEV }}
          DSCI_AZ_SAS_PROD: ${{ secrets.DSCI_AZ_SAS_PROD }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up environment
              uses: ocha-dap/hdx-signals-actions@v2

            - name: First, update locations we cover
              shell: bash
              run: Rscript ./src-static/update_locations.R

            - name: Update adm0 data for all locations
              shell: bash
              run: Rscript ./src-static/update_adm0_sf.R

            - name: Update adm0 centroid for all locations
              shell: bash
              run: Rscript ./src-static/update_centroids_sf.R

            - name: Update cities data for all locations
              shell: bash
              run: Rscript ./src-static/update_cities_sf.R

            - name: Update HRP classifications for all locations
              shell: bash
              run: Rscript ./src-static/update_hrp.R

            - name: Update locations metadata after previous updates
              shell: bash
              run: Rscript ./src-static/update_locations_metadata.R
